baseURL = "https://gavinjakubik.me/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Gavin Jakubik"
theme = "hermit-V2"

pygmentsCodefences = true
pygmentsUseClasses = true

rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
buildDrafts = true

[author]
  name = "Gavin Jakubik"

[taxonomies]
  tag = "tags"

[params]
  author = { name = "Gavin Jakubik" }
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-2"
  dateformNumTime = "2006-01-2 15:04"
  footerHideThemeName = true
  
  themeColor = "#81f7f7"
  homeSubtitle = "UI Engineer @ SIMON Markets | CS @ ND"
  footerCopyright = ' CC BY-NC 4.0 '
  # bgImg = "background.png"
  justifyContent = false
  relatedPosts = false
  code_copy_button = true

  [[params.socialLinks]]
  name = "gitlab"
  url = "https://gitlab.com/gavin.jakubik"

  [[params.socialLinks]]
  name = "github"
  url = "https://github.com/gjakubik"

  [[params.socialLinks]]
  name = "linkedin"
  url = "https://linkedin.com/in/gavinjakubik"

[menu]

  [[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 10

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 20

  [[menu.main]]
  name = "Resume"
  url = "resume.pdf"
  weight = 20
